project:
  type: website

website:
  title: "analytics-log"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Projects
        menu:
          - href: projects/w1/report.qmd
            text: Week 1

format:
  html:
    theme:
      - darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
