# .github/workflows/quarto-publish.yml
name: Quarto Publish

on:
  push:
    branches: [ master ]           # change to 'main' if needed

# Permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Quarto
      - uses: quarto-dev/quarto-actions/setup@v2

      # Configure Pages
      - uses: actions/configure-pages@v5

      # Render the site
      - name: Render Quarto site
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: analytics-log

      # Upload the built site as a Pages artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: analytics-log/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
